name: RankDisplay
main: PixelGuy75\RankDisplay\Main
version: 1.0
api: [1.9.0, 2.0.0, 2.1.0]
load: POSTWORLD
author: PixelGuy75
description: "Displays rank next to displayname over skin"
depend:["PurePerms"]
